### ISSUE TITLE
Docker installation failing

### ISSUE THREAD

**Issue by prinshul** [geometric-intelligence/TopoBenchmark#106]
OS: Sonoma 14.4
Apple M3 Pro

18.71   Downloading sphinx-8.1.3-py3-none-any.whl.metadata (6.4 kB)
19.02 Collecting sphinx-gallery (from TopoBenchmark==0.0.1)
19.04   Downloading sphinx_gallery-0.18.0-py3-none-any.whl.metadata (8.9 kB)
19.43 Collecting pydata-sphinx-theme (from TopoBenchmark==0.0.1)
19.45   Downloading pydata_sphinx_theme-0.16.0-py3-none-any.whl.metadata (7.5 kB)
19.49 Collecting gudhi (from topomodelx@ git+https://github.com/pyt-team/TopoModelX.git->TopoBenchmark==0.0.1)
19.50   Downloading gudhi-3.8.0rc1.tar.gz (526 kB)
19.62      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 5.4 MB/s eta 0:00:00
19.65   Installing build dependencies: started
25.91   Installing build dependencies: finished with status 'done'
25.91   Getting requirements to build wheel: started
26.16   Getting requirements to build wheel: finished with status 'error'
26.16   error: subprocess-exited-with-error
26.16   
26.16   × Getting requirements to build wheel did not run successfully.
26.16   │ exit code: 1
26.16   ╰─> [25 lines of output]
26.16       Traceback (most recent call last):
26.16         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
26.16           main()
26.16         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
26.16           json_out['return_val'] = hook(**hook_input['kwargs'])
26.16                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
26.16         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
26.16           return hook(config_settings)
26.16                  ^^^^^^^^^^^^^^^^^^^^^
26.16         File "/tmp/pip-build-env-zhwynqd9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
26.16           return self._get_build_requires(config_settings, requirements=[])
26.16                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
26.16         File "/tmp/pip-build-env-zhwynqd9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 303, in _get_build_requires
26.16           self.run_setup()
26.16         File "/tmp/pip-build-env-zhwynqd9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 319, in run_setup
26.16           exec(code, locals())
26.16         File "<string>", line 47, in <module>
26.16         File "/tmp/pip-build-env-zhwynqd9/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1010, in cythonize
26.16           module_list, module_metadata = create_extension_list(
26.16                                          ^^^^^^^^^^^^^^^^^^^^^^
26.16         File "/tmp/pip-build-env-zhwynqd9/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 845, in create_extension_list
26.16           for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
26.16         File "/tmp/pip-build-env-zhwynqd9/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 117, in nonempty
26.16           raise ValueError(error_msg)
26.16       ValueError: 'D:/a/gudhi-devel/gudhi-devel/src/python/gudhi/off_utils.pyx' doesn't match any files
26.16       [end of output]
26.16   
26.16   note: This error originates from a subprocess, and is likely not a problem with pip.
26.17 error: subprocess-exited-with-error
26.17 
26.17 × Getting requirements to build wheel did not run successfully.
26.17 │ exit code: 1
26.17 ╰─> See above for output.
26.17 
26.17 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:9
--------------------
   7 |     RUN pip install --upgrade pip
   8 |     
   9 | >>> RUN pip install -e '.[all]'
  10 |     
  11 |     # Note that not all combinations of torch and CUDA are available
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -e '.[all]'" did not complete successfully: exit code: 1

The problem is while installing "gudhi" package.
ValueError: 'D:/a/gudhi-devel/gudhi-devel/src/python/gudhi/off_utils.pyx' doesn't match any files

**Comment by gbg141** [comment]
Hi @prinshul ! Thank you for reaching out, and apologies for the late reply; we've been discussing these last weeks whether to keep `docker` support or not.

Unfortunately, given that all contributors are using `conda` to develop the library, we decided to remove `docker` from our documentation --as we cannot ensure it is working/will properly work with the new updates.

Therefore, and unfortunately, we cannot help you with this particular issue. However, we highly recommend you to use the library through a `conda` environment, and we would be very pleased to answer any question or doubt you might have with it.
